repos:
- name: "microservices-demo"
  owner: "GoogleCloudPlatform"
  defaultbranch: "master"
- name: "bank-of-anthos"
  owner: "GoogleCloudPlatform"
  defaultbranch: "master"
- name: "kubernetes-engine-samples"
  owner: "GoogleCloudPlatform"
  defaultbranch: "master"
- name: "anthos-samples"
  owner: "GoogleCloudPlatform"
  defaultbranch: "master"
- name: "anthos-service-mesh-samples"
  owner: "GoogleCloudPlatform"
  defaultbranch: "master"
- name: "anthos-config-management-samples"
  owner: "GoogleCloudPlatform"
  defaultbranch: "main"
- name: "java-container"
  owner: "googleapis"
  defaultbranch: "master"
- name: "google-cloud-php-container"
  owner: "googleapis"
  defaultbranch: "master"
- name: "python-container"
  owner: "googleapis"
  defaultbranch: "master"
- name: "nodejs-cloud-container"
  owner: "googleapis"
  defaultbranch: "master"